"""first migration

Revision ID: f2d5bec3a112
Revises: 
Create Date: 2023-03-26 14:15:33.571755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2d5bec3a112'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urls',
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.Column('long', sa.String(), nullable=True),
    sa.Column('short', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id_')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('urls')
    # ### end Alembic commands ###
